name: 17wanxiaoCheckin

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
  schedule:
    - cron: 0 22,23 * * *

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Pip
      run: pip3 install requests pycryptodome
         
    - name: HealthyCheckIn
      run: |
        python3 index.py <<EOF
        ${{secrets.USERS}}
        EOF
        
