name: 17wanxiaoCheckin

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
  schedule:
    - cron: 0 22,23 * * *

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: 'Checkout codes'
      uses: actions/checkout@v2

    - name: 'Set up Python'
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: 'Install requirements'
      run: pip install -r requirements.txt
         
    - name: HealthyCheckIn
      run: |
        export http_proxy="http://llkhs:913782@155.94.128.124:8829"
        export https_proxy="http://llkhs:913782@155.94.128.124:8829"
        python3 index.py <<EOF
        ${{secrets.USERS}}
        EOF
      env:
        BILI_USER: ${{ secrets.BILI_USER }}
        PUSH_KEY: ${{ secrets.PUSH_KEY }}
        BARK_PUSH: ${{ secrets.BARK_PUSH }}
        QQ_SKEY: ${{ secrets.QQ_SKEY}}
        QQ_MODE: ${{ secrets.QQ_MODE}}
        TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
        TG_USER_ID: ${{ secrets.TG_USER_ID }}
        BARK_SOUND: ${{ secrets.BARK_SOUND }}
        DD_BOT_TOKEN: ${{ secrets.DD_BOT_TOKEN }}
        DD_BOT_SECRET: ${{ secrets.DD_BOT_SECRET }}
